# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afe90306276657718fa95963b787fa3bfd45f4af8131f14355935d54f7f87888532388be85203a6aebba5effa27488d3ce10190155654e9bc73efcb6d1884120

test:
  secret_key_base: 502a03efc9545b2ae67cc406eff977535db9f958a677a188cab43f09b80abb9399a748eac1e766288786735b46ec0bf80ba92df472c2be6d9fd981bf88568f46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
